//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActualizacionDatos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Familia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Familia()
        {
            this.CargoPublico = new HashSet<CargoPublico>();
            this.FamiliaEstado = new HashSet<FamiliaEstado>();
            this.Hermano = new HashSet<Hermano>();
        }
    
        public int Co_Familia { get; set; }
        public string No_Usuario { get; set; }
        public string Tx_NombresPadre { get; set; }
        public string Tx_ApellidoPatPadre { get; set; }
        public string Tx_ApellidoMatPadre { get; set; }
        public string Tx_NombresMadre { get; set; }
        public string Tx_ApellidoPatMadre { get; set; }
        public string Tx_ApellidoMatMadre { get; set; }
        public Nullable<int> Fl_CosanguiniedadEstado { get; set; }
        public Nullable<System.DateTime> Fe_Registro { get; set; }
        public Nullable<int> Fl_CargoPublico { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CargoPublico> CargoPublico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FamiliaEstado> FamiliaEstado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hermano> Hermano { get; set; }
    }
}
