//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActualizacionDatos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hermano
    {
        public int Co_Hermano { get; set; }
        public Nullable<int> Co_Familia { get; set; }
        public string Tx_NombresHermano { get; set; }
        public string Tx_ApellidoPatHermano { get; set; }
        public string Tx_ApellidoMatHermano { get; set; }
        public Nullable<System.DateTime> Fe_Registro { get; set; }
    
        public virtual Familia Familia { get; set; }
    }
}
