//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActualizacionDatos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hermano
    {
        public int Co_Hermano { get; set; }
        public Nullable<int> Co_Familia { get; set; }
        public string Tx_NombresHermano { get; set; }
        public string Tx_ApellidoPatHermano { get; set; }
        public string Tx_ApellidoMatHermano { get; set; }
        public Nullable<System.DateTime> Fe_Registro { get; set; }
    
        public virtual Familia Familia { get; set; }
    }
}
