//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActualizacionDatos.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IntranetEntities : DbContext
    {
        public IntranetEntities()
            : base("name=IntranetEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CargoPublico> CargoPublico { get; set; }
        public virtual DbSet<Familia> Familia { get; set; }
        public virtual DbSet<FamiliaEstado> FamiliaEstado { get; set; }
        public virtual DbSet<Hermano> Hermano { get; set; }
    }
}
