//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActualizacionDatos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int Co_Usuario { get; set; }
        public Nullable<int> Co_Foto { get; set; }
        public string No_Usuario { get; set; }
        public string Tx_Nombre { get; set; }
        public string Tx_ApellidoPaterno { get; set; }
        public string Tx_ApellidoMaterno { get; set; }
        public string Tx_NombreCorto { get; set; }
        public string Tx_Iniciales { get; set; }
        public string Tx_NombreCompleto { get; set; }
        public string Tx_NombreAlertaCumple { get; set; }
        public Nullable<System.DateTime> Fe_Nacimiento { get; set; }
        public Nullable<System.DateTime> Fe_NacimientoCompleta { get; set; }
        public Nullable<int> Co_TipoUsuario { get; set; }
        public Nullable<int> Co_AreaPractica { get; set; }
        public Nullable<int> Co_Cargo { get; set; }
        public string Tx_Anexo { get; set; }
        public string Tx_Directo { get; set; }
        public string Tx_Movil { get; set; }
        public string Tx_Correo { get; set; }
        public string Tx_Piso { get; set; }
        public string Tx_PisoPosicion { get; set; }
        public Nullable<int> Fl_Activo { get; set; }
        public Nullable<int> Fl_DNI { get; set; }
        public string Tx_RutaDNI { get; set; }
        public Nullable<int> Co_ColegioAbogados { get; set; }
        public Nullable<int> Nu_Colegiatura { get; set; }
        public string Fl_Sexo { get; set; }
        public Nullable<int> Co_TipoDocumento { get; set; }
        public string Nu_Documento { get; set; }
        public string No_Pais { get; set; }
        public string No_Ciudad { get; set; }
        public string Fl_EstadoCivil { get; set; }
        public string Tx_Sede { get; set; }
        public string Tx_CuentaSUNARP { get; set; }
        public string Tx_Secretaria { get; set; }
    }
}
